[pytest]
filterwarnings =
    ignore::DeprecationWarning:pandas_datareader.*
    ignore:Maximum Likelihood optimization failed to converge.*:statsmodels.tools.sm_exceptions.ConvergenceWarning
    ignore:invalid value encountered in sqrt:RuntimeWarning:statsmodels.*
