from __future__ import annotations
from api.guide import (
    _fallback_blueprint,
    _statistical_battery,
    _leakage_policy,
    _economic_significance,
    _reviewer_gate,
    VALID_METHOD_FAMILIES,
)


def test_directional_comparative_hypothesis_is_confirmatory():
    """
    Any brief containing a directional comparison between 
    conditions must be classified as confirmatory.
    Uses abstract placeholder language, not a real topic.
    """
    payload = {
        "topic": (
            "Does condition A produce outcome X at a higher "
            "rate than condition B when controlling for Z? "
            "This study compares two market regimes to test "
            "whether regime A amplifies outcome X relative "
            "to regime B."
        )
    }
    result = _fallback_blueprint(payload)
    summary = result["blueprint_summary"]
    # Directional comparative question must not be exploratory
    assert summary["research_stance"] in {
        "confirmatory", "confirmatory_pap"
    } or summary["method_style"] != "descriptive", (
        "Directional comparative hypothesis must not be "
        "classified as exploratory descriptive"
    )


def test_synthetic_data_study_does_not_infer_yfinance():
    """
    A study that generates its own data must not suggest 
    yfinance as the evidence route.
    Uses abstract placeholder language.
    """
    payload = {
        "topic": (
            "This study uses a synthetic market environment "
            "where agents interact according to learned "
            "strategies. The data is generated by the "
            "simulation, not sourced from external providers."
        )
    }
    result = _fallback_blueprint(payload)
    summary = result["blueprint_summary"]
    assert summary["evidence_source"] != "yfinance", (
        "Simulation study must not infer yfinance as evidence"
    )


def test_multi_agent_keyword_infers_non_descriptive_method():
    """
    A study involving multiple interacting agents must not 
    be classified as descriptive.
    """
    payload = {
        "topic": (
            "Multi-agent system with emergent market behaviour. "
            "Agents interact and generate order flow. "
            "Testing whether homogeneous agent strategies "
            "amplify market instability."
        )
    }
    result = _fallback_blueprint(payload)
    summary = result["blueprint_summary"]
    assert summary["method_style"] != "descriptive", (
        "Multi-agent study must not be classified as descriptive"
    )


def test_network_keywords_infer_non_descriptive_method():
    """
    A study involving contagion and interconnectedness 
    must not be classified as descriptive.
    """
    payload = {
        "topic": (
            "Does bilateral network topology among financial "
            "institutions predict contagion speed during "
            "stress events? Graph centrality measures applied "
            "to interbank exposure data."
        )
    }
    result = _fallback_blueprint(payload)
    summary = result["blueprint_summary"]
    assert summary["method_style"] != "descriptive", (
        "Network contagion study must not be descriptive"
    )


def test_text_corpus_keywords_infer_non_yfinance_evidence():
    """
    A study using earnings transcripts must not suggest 
    yfinance as the primary evidence route.
    """
    payload = {
        "topic": (
            "Using earnings call transcripts and NLP sentiment "
            "analysis to predict subsequent abnormal returns. "
            "Text corpus from quarterly earnings calls."
        )
    }
    result = _fallback_blueprint(payload)
    summary = result["blueprint_summary"]
    assert summary["evidence_source"] in {
        "text_corpus", "edgar_yfinance", "upload"
    }, (
        f"Text study should not suggest yfinance alone, "
        f"got {summary['evidence_source']}"
    )


def test_statistical_battery_covers_all_method_families():
    """Every method family must have at least 3 tests."""
    for method in VALID_METHOD_FAMILIES:
        battery = _statistical_battery(method)
        assert battery.get("tests"), (
            f"Empty test battery for: {method}"
        )
        assert len(battery["tests"]) >= 3, (
            f"Fewer than 3 tests for: {method}"
        )


def test_leakage_policy_covers_all_method_families():
    """Every method family must have a leakage rule."""
    for method in VALID_METHOD_FAMILIES:
        policy = _leakage_policy(method)
        assert policy.get("primary_rule"), (
            f"Missing leakage rule for: {method}"
        )


def test_economic_significance_covers_all_method_families():
    """Every method family must have an economic significance rule."""
    for method in VALID_METHOD_FAMILIES:
        sig = _economic_significance(method)
        assert sig.get("rule"), (
            f"Missing economic significance for: {method}"
        )


def test_reviewer_gate_method_focus_covers_all_families():
    """Every method family must have at least 3 reviewer dimensions."""
    for method in VALID_METHOD_FAMILIES:
        gate = _reviewer_gate(False, method)
        focus = gate.get("method_focus", [])
        assert isinstance(focus, list) and len(focus) >= 3, (
            f"Insufficient reviewer focus for: {method}"
        )
