from __future__ import annotations

import json
from pathlib import Path

from fastapi.testclient import TestClient


TOPIC = """Multi-Agent AI Systems and Flash Crash Amplification: A Market Microstructure Simulation

When a non-trivial fraction of intraday order flow is generated by AI agents sharing similar learned strategies, does correlated agent behaviour amplify flash crash frequency and severity relative to a market populated by heterogeneous human traders?"""


MENTOR_TOPICS = {
    "tail_risk_momentum": (
        "Tail Risk Conditioning and the Survival of Momentum Strategies Across Market Regimes. "
        "Does conditioning sector ETF momentum strategy allocation on real-time tail risk indicators "
        "allow strategies to avoid momentum crashes while preserving upside capture during normal regimes?"
    ),
    "sec_filing_language": (
        "LLM-Powered RegTech: Automated SEC Filing Risk Monitoring and Overnight Volatility Forecasting. "
        "Do material changes in forward-looking risk language in SEC filings detected by embedding-space "
        "distance metrics from a large language model pipeline predict elevated overnight volatility?"
    ),
    "earnings_call_sentiment": (
        "LLM Earnings-Call Sentiment and Overnight Return Predictability in Sector ETFs. "
        "Do nuanced sentiment signals extracted by large language models from quarterly earnings call transcripts "
        "predict the overnight gap return after controls?"
    ),
    "agent_flash_crash": TOPIC,
    "etf_arbitrage_half_life": (
        "ETF Creation-Redemption Arbitrage Cycles and the Decay of Intraday Price Efficiency. "
        "What is the intraday half-life of ETF open-price deviations from net asset value, and does daytime "
        "mean-reversion reflect mechanical closure of creation/redemption arbitrage gaps?"
    ),
}


def test_research_architect_classifies_mentor_topics_without_demo_lock_in() -> None:
    from api import guide

    expected = {
        "tail_risk_momentum": ("backtest", "yfinance"),
        "sec_filing_language": ("text_analysis", "edgar_yfinance"),
        "earnings_call_sentiment": ("text_analysis", "text_corpus"),
        "agent_flash_crash": ("agent_based_model", "simulation_generated"),
        "etf_arbitrage_half_life": ("regression", "yfinance"),
    }
    for key, topic in MENTOR_TOPICS.items():
        summary = guide.validate({"topic": topic})["blueprint_summary"]
        method, evidence = expected[key]
        assert summary["method_style"] == method, key
        assert summary["evidence_source"] == evidence, key


def _client(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("ENVIRONMENT", "test")
    monkeypatch.setenv("SQLITE_DB_PATH", str(tmp_path / "topic4-sessions.db"))
    monkeypatch.setenv("THRIVARC_STORAGE_BACKEND", "mock")
    from storage import blob

    blob.reset_mock_storage()
    from main import app

    return TestClient(app)


def test_topic4_website_to_backend_to_publishable_package(tmp_path: Path, monkeypatch) -> None:
    client = _client(tmp_path, monkeypatch)

    created = client.post("/api/sessions", json={"topic": TOPIC, "domain": "finance_economics", "file_refs": []})
    assert created.status_code == 200
    session_id = created.json()["session_id"]

    scoped = client.patch(
        f"/api/sessions/{session_id}/scope",
        json={
            "research_type": "confirmatory",
            "focus_question": TOPIC,
            "hypothesis": "Correlated AI-agent order flow increases flash crash frequency and severity relative to heterogeneous human order flow.",
            "constraints": {
                "evidence": "simulation-generated intraday order book paths",
                "design": "agent-based market microstructure simulation with locked stress scenarios",
                "target": "defensible research paper",
            },
            "target_outcome": "paper",
        },
    )
    assert scoped.status_code == 200

    blueprint = client.get(f"/api/sessions/{session_id}/blueprint").json()
    assert blueprint["research_package"]["track"] == "confirmatory"
    assert blueprint["method_family"] == "agent_based_model"
    assert blueprint["evidence_source"] == "simulation_generated"
    assert blueprint["completion_contract"]["ready_for_evidence_preview"] is True

    locked = client.post(f"/api/sessions/{session_id}/blueprint/lock", json={"confirmation": "CONFIRM"})
    assert locked.status_code == 200
    assert locked.json()["blueprint_hash"]

    preview_patch = client.patch(
        f"/api/sessions/{session_id}/blueprint",
        json={"data_preview_sha256": "preview-sha-topic4", "preview_run_id": "preview-run-topic4"},
    )
    assert preview_patch.status_code == 200

    launched = client.post(f"/api/sessions/{session_id}/run", json={"approved": True})
    assert launched.status_code == 200
    assert launched.json()["run_started"] is True

    session = client.get(f"/api/sessions/{session_id}").json()
    assert session["status"] == "paper_unlocked"
    assert {phase["status"] for phase in session["phases"]} == {"complete"}

    results = client.get(f"/api/sessions/{session_id}/results").json()
    assert results["reviewer_scores"][-1]["gate_passed"] in {1, True}
    assert results["reviewer_scores"][-1]["average_score"] >= 7.0
    assert results["paper_url"]
    assert results["integrity_artifacts"]

    artifacts = client.get(f"/api/sessions/{session_id}/artifacts").json()["artifacts"]
    paths = {item["path"] for item in artifacts}
    required_suffixes = {
        "01_integrity/truth_contract.json",
        "02_literature/synthesis.json",
        "03_data/data_passport.json",
        "04_features/feature_manifest.json",
        "05_preregistration/" + "pap" + "_lock_certificate.json",
        "07_statistics/economic_significance.json",
        "08_audit/code_audit_report.md",
        "08_audit/spec_audit_report.md",
        "09_review/reviewer_scorecard_v1.json",
        "10_verification/paper_code_verification.json",
        "11_paper/final.tex",
        "11_paper/final.pdf",
    }
    for suffix in required_suffixes:
        assert any(path.endswith(suffix) for path in paths), suffix

    from storage.blob import read_artifact

    compute_paths = [path for path in paths if "/06_compute/method_outputs/" in path and path.endswith("_results.json")]
    assert compute_paths
    sim = json.loads(read_artifact(session_id, compute_paths[0].split(f"sessions/{session_id}/", 1)[1]))
    assert sim["method_family"] == "agent_based_model"
    assert sim["primary_numbers"]

    verifier = json.loads(read_artifact(session_id, "10_verification/paper_code_verification.json"))
    assert verifier["status"] == "verified"
    assert verifier["numbers_verified"] is True

    paper = read_artifact(session_id, "11_paper/final.tex").decode("utf-8")
    assert "flash crash" in paper.lower()
    assert "\\documentclass[12pt]" in paper
    assert "\\begin{table}" in paper
    assert "TBD" not in paper and "[INSERT NUMBER]" not in paper

    stream_text = client.get(f"/api/sessions/{session_id}/stream").text
    assert "gate_result" in stream_text
    assert "writer_unlocked" in stream_text
    assert "run_complete" in stream_text


def test_legacy_website_run_urls_delegate_to_canonical_session_pipeline(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.delenv("THRIVARC_ENABLE_LEGACY_RUNS", raising=False)
    client = _client(tmp_path, monkeypatch)

    created = client.post(
        "/runs/create",
        json={
            "topic": TOPIC,
            "hypothesis": "Correlated AI-agent order flow increases flash crash frequency and severity.",
            "approach": "confirmatory",
            "output_format": "paper",
            "connector": "simulation_generated",
            "data_confirmed": True,
            "data_preview_sha256": "preview-sha-legacy",
        },
    )
    assert created.status_code == 200
    run_id = created.json()["run_id"]

    status = client.get(f"/runs/{run_id}/status")
    assert status.status_code == 200
    body = status.json()
    assert body["status"] == "paper_unlocked"
    assert body["reviewer_gate"]["passed"] is True
    assert "WRITER" in body["phases_completed"]

    session = client.get(f"/api/sessions/{run_id}")
    assert session.status_code == 200
    assert session.json()["status"] == "paper_unlocked"

    findings = client.get(f"/runs/{run_id}/findings").json()["findings"]
    assert findings["validity"]
    assert findings["key_numbers"]

    reviewer = client.get(f"/runs/{run_id}/reviewer_report").json()
    assert reviewer["score"] >= 7.0
    assert reviewer["weaknesses"]

    paper = client.get(f"/runs/{run_id}/paper").json()
    assert paper["draft_url"]
    assert paper["paper"]["thrivarc"]["methodology"]

    artifacts = client.get(f"/runs/{run_id}/artifacts").json()["artifacts"]
    assert any(item["path"].endswith("11_paper/final.pdf") for item in artifacts)
